# roles/postgres/tasks/main.yml

- name: Установить PostgreSQL и зависимости
  apt:
    name:
      - postgresql
      - python3-psycopg2
      - libpq-dev
      - python3-pip
    state: present

- name: Установить psycopg2 через pip
  pip:
    name: psycopg2-binary
    executable: pip3

- name: Запустить PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Убедиться, что база данных создана
  become_user: postgres
  community.postgresql.postgresql_db:
    name: example_db
    state: present

- name: Убедиться, что таблица example_table создана и данные вставлены
  become_user: postgres
  community.postgresql.postgresql_query:
    db: example_db
    query: |
      CREATE TABLE IF NOT EXISTS example_table (
        id SERIAL PRIMARY KEY,
        name VARCHAR(50)
      );
      INSERT INTO example_table (name)
      VALUES ('example1'), ('example2'), ('example3')
      ON CONFLICT (id) DO NOTHING;

