---
- name: Установить Docker
  apt:
    name: docker.io
    state: present

- name: Установить pip
  apt:
    name: python3-pip
    state: present

- name: Установить Docker Compose как бинарный файл
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Копировать файл docker-compose с менеджера на node01
  copy:
    src: /home/vagrant/docker-compose.yml
    dest: /home/vagrant/docker-compose.yml
    mode: '0644'

- name: Запустить Docker Compose
  command: docker-compose up -d
  args:
    chdir: /home/vagrant/
