---
- name: Ensure Python3 and pip are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip
  become: yes

- name: Install psycopg2
  pip:
    name: psycopg2-binary
    state: present
    executable: pip3
  become: yes

- name: Ensure PostgreSQL is installed
  apt:
    name: postgresql-14
    state: present
  become: yes

- name: Start and enable PostgreSQL service
  systemd:
    name: postgresql
    enabled: yes
    state: started
  become: yes

# Временно изменяем метод аутентификации на 'trust'
- name: Temporarily update pg_hba.conf to use trust authentication
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+\w+'
    line: 'local   all             postgres                                trust'
  become: yes

- name: Restart PostgreSQL service to apply 'trust' authentication
  systemd:
    name: postgresql
    state: restarted
  become: yes

- name: Set PostgreSQL password for user postgres
  postgresql_user:
    name: postgres
    password: "postgres"  # Задайте новый пароль
  become: yes

# Возвращаем метод аутентификации на 'md5'
- name: Update pg_hba.conf to use md5 authentication
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+\w+'
    line: 'local   all             postgres                                md5'
  become: yes

- name: Restart PostgreSQL service to apply 'md5' authentication
  systemd:
    name: postgresql
    state: restarted
  become: yes

- name: Create database hotels_db
  postgresql_db:
    name: hotels_db
    state: present
    login_user: postgres
    login_password: "postgres"  # Новый установленный пароль
  become: yes
  
