---
- name: Обновить список пакетов
  apt:
    update_cache: yes

- name: Установить Apache
  apt:
    name: apache2
    state: present

- name: Запустить Apache
  service:
    name: apache2
    state: started
    enabled: yes
